[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sebcel-transcribe-cli"
version = "0.1.0"
description = "CLI for sebcel-transcribe-pipeline"
dependencies = [
  "boto3",
  "typer",
]

[project.scripts]
transcribe = "transcribe_cli.cli:app"